name: Mirror the terraform provider assets from chanzuckerberg/happy

on:
  # this is the main way to trigger the workflow, the .github/workflows/provider-release.yaml in the happy repo 
  # calls createWorkflowDispatch after the goreleaser step has completed
  workflow_dispatch: {}
  schedule:
    # run on a schedule in case the workflow_dispatch fails
    - cron: "0 8 * * *"

jobs:
  build:
    name: Mirror
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  
      - run: ./mirror.sh
        env:
          GH_TOKEN: ${{ github.token }}
