name: Mirror the terraform provider assets from chanzuckerberg/happy

on:
  schedule:
    # Runs "every 15th minute" (see https://crontab.guru)
    - cron: "*/15 * * * *"
jobs:
  build:
    name: Mirror
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  
      - run: ./mirror.sh