name: Mirror the terraform provider assets from chanzuckerberg/happy

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Mirror
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'  
      - run: ./mirror.sh
        env:
          GH_TOKEN: ${{ github.token }}
